# Site settings
title:          Our Healthcare HK
description:    "Raising awareness for the healthcare system in Hong Kong"
baseurl:        ""
url:            "https://OurHealthcareHK.github.io/tabler"

# Author
author:
  name:         Mister Mochi
  url:          https://github.com/mistermochi
  email:        mochitravels@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed
